In [2]:
import numpy as np
# np is the context manager for numpy

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)


numpy.ndarray

In [4]:
a.ndim

1

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # list of list
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# create an array of zeros
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones([2,2])
# array of ones

array([[1., 1.],
       [1., 1.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.arange(10) # start from 0 t0 10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5,16) # start, end point
# array of evenly spaced numbers

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.arange(2,16,3) # start,end,step

array([ 2,  5,  8, 11, 14])

In [13]:
#generate linear data
np.linspace(5,21,16) # start , end , number of values

array([ 5.        ,  6.06666667,  7.13333333,  8.2       ,  9.26666667,
       10.33333333, 11.4       , 12.46666667, 13.53333333, 14.6       ,
       15.66666667, 16.73333333, 17.8       , 18.86666667, 19.93333333,
       21.        ])

In [14]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a)
print()
print(b)

np.concatenate((a,b))

[1 2 3 4]

[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x = np.array([[1,2],[3,4],[7,8]])
y = np.array([[5,6],[9,10]])

print(x)
print()
print(y)
np.concatenate((x,y))

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
np.concatenate((x,y),axis = 0)
# axis 0 (row) is vertical axis because in this we go top to bottom (default)
# and axis 1(column) is horizontal axis because in this we go left to right

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
x = np.array([[1,2],[3,4],[7,8]])
y = np.array([[5,6],[9,10],[4,6]])

print(x)
print()
print(y)

np.concatenate((x,y),axis = 1)

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]
 [ 4  6]]


array([[ 1,  2,  5,  6],
       [ 3,  4,  9, 10],
       [ 7,  8,  4,  6]])

In [19]:
x = np.array([[1,2],[3,4]])
y = np.array([[5],[6]])
# number of row should be equal but not for columns
print(x)
print()
print(y)
np.concatenate((x,y),axis = 1)

[[1 2]
 [3 4]]

[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [24]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,8,1],[6,3,7]])
# number of row should be equal but not for columns
print(x)
print()
print(y)
np.concatenate((x,y),axis = 1)

[[1 2]
 [3 4]]

[[5 8 1]
 [6 3 7]]


array([[1, 2, 5, 8, 1],
       [3, 4, 6, 3, 7]])

In [ ]:
import numpy as np
#splitting
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3) # here 3 = number of parts in which array divide
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [7]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,10)
print(newarr)
print(newarr[0])
print(newarr[1])

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]
[1]
[2]


In [ ]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[6,3],[9,2]])
print(arr)
newarr = np.array_split(arr,3,axis =0) # row wise split
print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [6 3]
 [9 2]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[6, 3],
       [9, 2]])]


In [10]:
# split a 2d array into three 2d array along row/across columns

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
newarr = np.array_split(arr,3,axis=1) # split through columns
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
newarr = np.split(arr,3) # divide all array of equal size
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [17]:
arr = np.array([2,1,5,3,8,5,7])
x = np.sort(arr)
print(x)

[1 2 3 5 5 7 8]


In [20]:
arr[::-1]

array([7, 5, 8, 3, 5, 1, 2])

In [23]:
#where # returning the positions(index values)
arr = np.array([1,2,3,4,5,4,4])
x  = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [24]:
x = np.where(arr%2 ==0)
print(x)

(array([1, 3, 5, 6]),)


In [25]:
arr1 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr1)

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
arr1.ndim #dimension

2

In [27]:
arr1.size #total number of elements present in array


8

In [ ]:
arr1.shape # provide row and column

(2, 4)

In [ ]:
# transpose of an array
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [30]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [33]:
#flatten
a = np.array([[1,2],[3,4]])
a


array([[1, 2],
       [3, 4]])

In [34]:
a.flatten() #convert array into 1D

array([1, 2, 3, 4])

In [35]:
# reshaping of an array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2,3) # row,column

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(-1,2) # -1 means m number of column(2) dunga but khud se computer number of row nikal lega

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# 1d to 3d (outerdimension)
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3) #no. of arrays,no.of rows,no. of columns
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a = np.arange(72)
a = np.reshape(a,(4,3,2,3)) #no. of blocks,arrays in each block,rows,columns
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])