In [2]:
import numpy as np
# np is the context manager for numpy

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)


numpy.ndarray

In [4]:
a.ndim

1

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # list of list
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# create an array of zeros
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones([2,2])
# array of ones

array([[1., 1.],
       [1., 1.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.arange(10) # start from 0 t0 10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5,16) # start, end point
# array of evenly spaced numbers

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.arange(2,16,3) # start,end,step

array([ 2,  5,  8, 11, 14])

In [13]:
#generate linear data
np.linspace(5,21,16) # start , end , number of values

array([ 5.        ,  6.06666667,  7.13333333,  8.2       ,  9.26666667,
       10.33333333, 11.4       , 12.46666667, 13.53333333, 14.6       ,
       15.66666667, 16.73333333, 17.8       , 18.86666667, 19.93333333,
       21.        ])

In [14]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a)
print()
print(b)

np.concatenate((a,b))

[1 2 3 4]

[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x = np.array([[1,2],[3,4],[7,8]])
y = np.array([[5,6],[9,10]])

print(x)
print()
print(y)
np.concatenate((x,y))

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [16]:
np.concatenate((x,y),axis = 0)
# axis 0 (row) is vertical axis because in this we go top to bottom (default)
# and axis 1(column) is horizontal axis because in this we go left to right

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [17]:
x = np.array([[1,2],[3,4],[7,8]])
y = np.array([[5,6],[9,10],[4,6]])

print(x)
print()
print(y)

np.concatenate((x,y),axis = 1)

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]
 [ 4  6]]


array([[ 1,  2,  5,  6],
       [ 3,  4,  9, 10],
       [ 7,  8,  4,  6]])

In [18]:
x = np.array([[1,2],[3,4]])
y = np.array([[5],[6]])
# number of row should be equal but not for columns
print(x)
print()
print(y)
np.concatenate((x,y),axis = 1)

[[1 2]
 [3 4]]

[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [19]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,8,1],[6,3,7]])
# number of row should be equal but not for columns
print(x)
print()
print(y)
np.concatenate((x,y),axis = 1)

[[1 2]
 [3 4]]

[[5 8 1]
 [6 3 7]]


array([[1, 2, 5, 8, 1],
       [3, 4, 6, 3, 7]])

In [20]:
import numpy as np
#splitting
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3) # here 3 = number of parts in which array divide
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
arr = np.array([1,2,3,4,5,6])
print(arr)
newarr = np.array_split(arr,4)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [22]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,10)
print(newarr)
print(newarr[0])
print(newarr[1])

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]
[1]
[2]


In [23]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[6,3],[9,2]])
print(arr)
newarr = np.array_split(arr,3,axis =0) # row wise split
print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [6 3]
 [9 2]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[6, 3],
       [9, 2]])]


In [24]:
# split a 2d array into three 2d array along row/across columns

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
newarr = np.array_split(arr,3,axis=1) # split through columns
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [26]:
newarr = np.split(arr,3) # divide all array of equal size
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [27]:
arr = np.array([2,1,5,3,8,5,7])
x = np.sort(arr)
print(x)

[1 2 3 5 5 7 8]


In [28]:
arr[::-1]

array([7, 5, 8, 3, 5, 1, 2])

In [29]:
#where # returning the positions(index values)
arr = np.array([1,2,3,4,5,4,4])
x  = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [30]:
x = np.where(arr%2 ==0)
print(x)

(array([1, 3, 5, 6]),)


In [31]:
arr1 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr1)

[[1 2 3 4]
 [4 5 6 7]]


In [32]:
arr1.ndim #dimension

2

In [33]:
arr1.size #total number of elements present in array


8

In [34]:
arr1.shape # provide row and column

(2, 4)

In [35]:
# transpose of an array
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [37]:
#flatten
a = np.array([[1,2],[3,4]])
a


array([[1, 2],
       [3, 4]])

In [38]:
a.flatten() #convert array into 1D

array([1, 2, 3, 4])

In [39]:
a.flatten('F')

array([1, 3, 2, 4])

In [50]:
# reshaping of an array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [51]:
a.reshape(2,3) # row,column

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
a.reshape(-1,2) # -1 means m number of column(2) dunga but khud se computer number of row nikal lega

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# 1d to 3d (outerdimension)
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3) #no. of arrays,no.of rows,no. of columns
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a = np.arange(72)
a = np.reshape(a,(4,3,2,3)) #no.of blocks,arrays in each block,rows,columns
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [3]:
import numpy as np
arr=np.arange(10)
newarr = np.split(arr, 5)  #this method works on equal distribution
print(newarr)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [4]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

print(a1, a2, sep="\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
a1+a2

array([[ 6,  8],
       [10, 12]])

In [6]:
a1-a2

array([[-4, -4],
       [-4, -4]])

In [7]:
a1*a2

array([[ 5, 12],
       [21, 32]])

In [9]:
a1/a2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [10]:
a1//a2

array([[0, 0],
       [0, 0]])

In [ ]:
a1.dot(a2)  # mathematics matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6]])  # this case of unequal array is possible

print(a1)
print(a2)


[[1 2]
 [3 4]]
[[5 6]]


In [14]:
a1+a2

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
a1 = np.array([[1,2],[3,4]])        # array should be of same shape and dimension except upper case of one element in 2d array
a2 = np.array([[5,6],[7,8],[3,6]])

a1+a2

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [16]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [17]:
a.max()

np.int64(4)

In [18]:
a.min()

np.int64(1)

In [19]:
a = np.array([[5,6],[7,8],[8,9]])
a

array([[5, 6],
       [7, 8],
       [8, 9]])

In [20]:
a.max()

np.int64(9)

In [ ]:
a.max(axis=0) #vertical (top to botttom)

array([8, 9])

In [ ]:
a.max(axis=1) # horizontal (left to right)

array([6, 8, 9])

In [23]:
a.sum()

np.int64(43)

In [24]:
a.sum(axis=0)

array([20, 23])

In [25]:
a.sum(axis=1)

array([11, 15, 17])

In [ ]:
np.mean(a,axis=0) #horizontal

array([6.66666667, 7.66666667])

In [ ]:
np.mean(a,axis=1) #vertical

array([5.5, 7.5, 8.5])

In [29]:
np.median(a,axis=0)

array([7., 8.])

In [30]:
np.median(a,axis=1)

array([5.5, 7.5, 8.5])

### fetching elements based on conditions

In [31]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(a[a<5])
# within [] write the conditional expression

[1 2 3 4]


In [33]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [ ]:
print(a[(a>2) & (a<11)])
# and operator - all condition must be satisfied

[ 3  4  5  6  7  8  9 10]


In [ ]:
print(a[(a>2) | (a<11)])
# or operator - atleast one codition should be true

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## indexing and slicing

In [39]:
dataone = np.array([[1,2],[3,4],[5,6]])
dataone

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
dataone[0] # row index position

array([1, 2])

In [ ]:
dataone[0,1] # o row 1 column

np.int64(2)

In [ ]:
dataone[:,1] # all rows and 1st index column

array([2, 4, 6])

In [45]:
dataone

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
dataone[1,0:2]

array([3, 4])

In [ ]:
dataone[0:2,1]   

array([2, 4])

In [46]:
dataone[0:1,0:2]

array([[1, 2]])