## Assignment 1

In [31]:
import numpy as np

1. Array Construction
a. Create a 1D integer array a containing the values 10–25 (inclusive) using np.arange.
b. Build a 3×4 array b of zeros and a 2×3 array c of ones (both integer dtype).

In [37]:
arr = np.arange(10,26)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [38]:
b=np.zeros([3,4])
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
c=np.ones([2,3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

2. Inspect &amp; Reshape
a. For each array (a, b, c), print its .shape and .dtype.
b. Reshape a into a 4×4 array a2. What happens if you try to reshape a into dimensions
that don’t match its size?

In [40]:
arr.shape

(16,)

In [41]:
b.shape

(3, 4)

In [42]:
c.shape

(2, 3)

In [43]:
arr.dtype

dtype('int64')

In [44]:
b.dtype

dtype('float64')

In [45]:
c.dtype

dtype('float64')

In [47]:
a2=arr.reshape(4,4)
a2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

Indexing &amp; Slicing
a. From a2, extract the second row and third column as separate 1D arrays.
b. Slice out the central 2×2 block of a2.

In [48]:
a2[1]

array([14, 15, 16, 17])

In [50]:
a2[:,3]

array([13, 17, 21, 25])

In [51]:
a2[1:3,1:3]

array([[15, 16],
       [19, 20]])

Element-Wise Arithmetic
a. Create two 2×2 arrays, x = [[1,2],[3,4]] and y = [[5,6],[7,8]].
b. Compute and print:
5. x + y
6. x - y
7. x * y
8. x / y
c. Create an array of ones with the same shape as a2 and add it to a2.

In [54]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [55]:
x + y

array([[ 6,  8],
       [10, 12]])

In [56]:
x - y

array([[-4, -4],
       [-4, -4]])

In [57]:
x * y

array([[ 5, 12],
       [21, 32]])

In [58]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [60]:
o = np.ones([4,4])
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
a2+o

array([[11., 12., 13., 14.],
       [15., 16., 17., 18.],
       [19., 20., 21., 22.],
       [23., 24., 25., 26.]])

## Assignment 2

a. Given the array d = np.array([3,8,1,6,0,6,9]), use np.where to find all indices where d is
even.

In [63]:
d = np.array([3,8,1,6,0,6,9])
d

array([3, 8, 1, 6, 0, 6, 9])

In [67]:
x=np.where(d%2==0)
print(x)

(array([1, 3, 4, 5]),)


b. Using boolean indexing, replace every value in d that is less than 5 with -1.

In [70]:
print(d[d<5])

[3 1 0]


Concatenation
a. Concatenate two 1D arrays
3. p = np.array([1,2,3])
4. q = np.array([4,5,6])
into a single array.
b. For 2D arrays
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
concatenate along axis=0 and then along axis=1.

In [73]:
p = np.array([1,2,3])
q = np.array([4,5,6])
np.concatenate((p,q))

array([1, 2, 3, 4, 5, 6])

In [75]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
np.concatenate((X,Y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Splitting
a. Split a 1D array r = np.arange(12) into three equal parts using np.split.
b. Split the same r into five parts using np.array_split. How does array_split handle uneven
splits?
c. Given a 2D array S of shape (6,2), split it into three subarrays along the first axis.

In [77]:
r = np.arange(12) 
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
np.split(r,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [79]:
np.array_split(r,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [ ]:
S = np.array([[1,2],[4,5],[6,7],[3,4],[9,8],[3,8]])
S

array([[1, 2],
       [4, 5],
       [6, 7],
       [3, 4],
       [9, 8],
       [3, 8]])

In [81]:
np.array_split(S,3)

[array([[1, 2],
        [4, 5]]),
 array([[6, 7],
        [3, 4]]),
 array([[9, 8],
        [3, 8]])]

Sorting &amp; Median
a. Create an unsorted 1D array of ten random integers between 0 and 50. Sort it with
np.sort.
b. Create a 3×4 array of random floats. Sort it row-wise (i.e. along axis=1).
c. Compute the median of your 3×4 array along axis=0 and along axis=1 using np.median.

In [83]:
arr1 = np.array([5,7,2,8,3,9,1,5])
np.sort(arr1)

array([1, 2, 3, 5, 5, 7, 8, 9])

In [84]:
arr2 = np.array([[3,6,4,6],[3,6,7,2],[7,2,9,4]])
arr2

array([[3, 6, 4, 6],
       [3, 6, 7, 2],
       [7, 2, 9, 4]])

In [85]:
np.sort(arr2,axis=1)

array([[3, 4, 6, 6],
       [2, 3, 6, 7],
       [2, 4, 7, 9]])

In [86]:
np.median(arr2,axis=0)

array([3., 6., 7., 4.])

In [88]:
np.median(arr2,axis=1)

array([5. , 4.5, 5.5])